# Site settings
title: Gaston Jouglard
description: Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gaston Jouglard
user_description: I am a Computer Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. With a strong background in software development spanning five years, I am currently working at Cladding Creations, an aluminum manufacturing company based in Gold Coast, Australia. There, I have been responsible for the development and maintenance of an app that streamlines inventory management and panel tracking. This has had a significant impact on data collection and error reduction. For a full history of my work experience, feel free to visit my LinkedIn profile.
user_title: Full Stack Developer
Argentina & Australia
email: gastonjouglard.10@gmail.com
# twitter_username: lorem_ipsum
instagram_username: gastonjou
# facebook_username: gaston.jouglard
linkedin_username: gastonjouglard
github_username:  gasti10
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']