# Site settings
title: Gaston Jouglard
description: Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gaston Jouglard
user_description: I am a Computer Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. With a strong background in software development spanning four years, I have been fully immersed in the world of heavy equipment, collaborating with Wymaq, a Buenos Aires-based startup. I'm the first engineer they hired to work on the platform, driving the digitization of the rental and management of heavy machinery in pursuit of making a positive impact on the world.
user_title: Full Stack Developer - Gold Coast QLD
email: gastonjouglard.10@gmail.com
# twitter_username: lorem_ipsum
instagram_username: gastonjou
facebook_username: gaston.jouglard
linkedin_username: gastonjouglard
github_username:  gasti10
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']